# Dataset configuration
dataset:
  name: 'pascal_voc'
  root_dir: 'datasets/data/pascal-voc'  # Updated to match your directory structure
  input_size: [512, 512]  # [height, width]
  num_classes: 21  # 20 classes + background
  ignore_index: 255
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  use_horizontal_flip: true

# Model configuration
model:
  name: 'unet'
  backbone: 'resnet50'
  pretrained: true
  in_channels: 3
  num_classes: 21
  head:
    type: 'semantic'
    dropout: 0.1

# Training configuration
training:
  epochs: 100
  batch_size: 2
  num_workers: 2
  optimizer:
    name: 'adam'
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    name: 'cosine'
    T_max: 100
    eta_min: 0.00001
  loss:
    name: 'cross_entropy'

# Validation configuration
validation:
  batch_size: 2
  num_workers: 2
  metrics:
    - 'miou'
    - 'pixel_accuracy'

# Logging configuration
logging:
  log_dir: 'logs'
  save_dir: 'checkpoints'
  log_interval: 10
  val_interval: 1
  save_interval: 5 